Hair 20
Brridge-Group/Golden-Gate-Hairr pull request #1
Opened 2021-08-25 17:06 UTC by cynthiaeddy

2021-08-25 17:32 UTC, cynthiaeddy commented
customer registration ui

2021-08-26 00:24 UTC, CodeMeKathy requested changes
Thank you for your great work and effort @cynthiaeddy!

2021-08-27 16:22 UTC, CodeMeKathy submitted a review, later dismissed

2021-09-14 01:36 UTC, CodeMeKathy approved these changes
Nice catch modifying the HTML input types.

2021-09-21 15:01 UTC, merged