Hair 66 store reviews backend
Brridge-Group/Golden-Gate-Hairr pull request #21
Opened 2021-12-15 20:23 UTC by cynthiaeddy

pr for capturing review in frontend and storing in db to the reviews, businesses, and users collections.

review in frontend for Stone Cutz:
<img width="989" alt="Screen Shot 2021-12-15 at 2 44 05 PM" src="https://user-images.githubusercontent.com/15850286/146258298-8b685f97-4698-40b0-b0a3-688fa36c96dc.png">
reviews collection (bottom review): _id:ObjectId(" 61ba458a1931834a109962ab")
<img width="834" alt="Screen Shot 2021-12-15 at 2 45 13 PM" src="https://user-images.githubusercontent.com/15850286/146258544-2351693e-b356-48dd-ba3f-2d370765ed7b.png">
businesses collection:  reviews: Array 1: ObjectId(" 61ba458a1931834a109962ab")
<img width="796" alt="Screen Shot 2021-12-15 at 2 46 09 PM" src="https://user-images.githubusercontent.com/15850286/146258981-65639590-c443-407f-af15-47ea63d6cc43.png">
users collection:  reviews: Array 7: ObjectId(" 61ba458a1931834a109962ab")
<img width="854" alt="Screen Shot 2021-12-15 at 2 46 47 PM" src="https://user-images.githubusercontent.com/15850286/146259368-5b19fd39-8a9d-477d-bcc0-828921e79f17.png">

2021-12-29 15:44 UTC, CodeMeKathy commented on controllers/businesses-controller.js
> -// Update Business
Was this deletion intentional?

2021-12-29 16:00 UTC, CodeMeKathy commented on package.json
> +    "dev": "nodemon server.js",
Hi, @cynthiaeddy! There is no server.js file.

2021-12-29 17:19 UTC, CodeMeKathy requested changes
Hi, @cynthiaeddy.  Great work; thank you for your efforts!  However, I am requesting changes and suggesting one minor change, as we discussed.  I suggest modifying or removing the changes made to the `package.json` file as there is no `server.js` file.

2022-01-02 20:05 UTC, cynthiaeddy commented on controllers/businesses-controller.js
> -// Update Business
probably not - put back in

2022-01-02 20:05 UTC, cynthiaeddy commented on package.json
> +    "dev": "nodemon server.js",
resolved

2022-01-02 20:13 UTC, cynthiaeddy commented
@CodeMeKathy hi! I updated package.json, so I guess you need to approve before I can merge?

2022-01-03 00:07 UTC, CodeMeKathy approved these changes
Thanks for making the changes @cynthiaeddy!! Happy New Year!!

2022-01-03 21:03 UTC, merged

2022-01-03 21:04 UTC, cynthiaeddy commented
@CodeMeKathy  pr merged. happy new year to you too!!